[package]
name = "rdhcp"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
env_logger = "0.6"
lazy_static = "1.5"
socket2 = "0.4"
