version: "3"
networks:
  static-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  dhcp-server:
    build: ./server
    privileged: true  # Required for network control
    volumes:
    - ./target/release/examples/dhcpd:/usr/local/bin/server
    networks:
      static-net:
        ipv4_address: 172.20.0.5

  dhcp-client:
    build: ./client
    privileged: true  # Required for network control
    volumes:
    - ./target/release/examples/dhcpd:/usr/local/bin/server
    depends_on:
    - dhcp-server
    networks:
      static-net:
        ipv4_address: 172.20.0.6
