name: AI Code Reviewer

on:
  pull_request:
    types:
    - opened
    - synchronize

permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true  # Enable debugging logs

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: AI Code Reviewer
      uses: juliankahlert/ai-codereviewer@bar
      with:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_MODEL: "gpt-4o"
        exclude: "**/*.json, **/*.md, **/*.toml, **/*.lock, **/*.yaml"

